DROP SCHEMA IF EXISTS CINEMA;
CREATE SCHEMA CINEMA;
USE CINEMA;

CREATE TABLE ENDERECO(
ID_ENDERECO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CIDADE VARCHAR(30),
ESTADO VARCHAR(30),
BAIRRO VARCHAR(50),
RUA VARCHAR(50),
NUMERO VARCHAR(10)
);

CREATE TABLE FILIAL(
ID_FILIAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_FANTASIA VARCHAR(255) NOT NULL,
ID_ENDERECO INT NOT NULL,
CONSTRAINT FK_ENDERECO_FILIAL
	FOREIGN KEY(ID_ENDERECO)
    REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE TABLE SALA(
ID_SALA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
LOTACAO VARCHAR(3),
ID_FILIAL INT NOT NULL,
CONSTRAINT FK_FILIAL_SALA
	FOREIGN KEY(ID_FILIAL)
    REFERENCES FILIAL(ID_FILIAL)
);

CREATE TABLE HORARIO(
ID_HORARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TURNO VARCHAR(255) NOT NULL,
HORARIO DATETIME NOT NULL
);

CREATE TABLE SESSAO(
ID_SESSAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_HORARIO INT NOT NULL,
CONSTRAINT FK_HORARIO_SESSAO
	FOREIGN KEY(ID_HORARIO)
    REFERENCES HORARIO(ID_HORARIO)
);

CREATE TABLE PESSOA(
ID_PESSOA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
NACIONALIDADE VARCHAR(255) NOT NULL,
DATA_NASCIMENTO DATETIME NOT NULL
);

CREATE TABLE DIRETOR(
ID_DIRETOR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PESSOA INT NOT NULL,
CONSTRAINT FK_PESSOA_DIRETOR
	FOREIGN KEY(ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
);

CREATE TABLE ATOR(
ID_ATOR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PESSOA INT NOT NULL,
CONSTRAINT FK_PESSOA_ATOR
	FOREIGN KEY(ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA)
);

CREATE TABLE FILME(
ID_FILME INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TITULO VARCHAR(255) NOT NULL,
GENERO VARCHAR(255) NOT NULL,
DURACAO VARCHAR(255) NOT NULL
);

CREATE TABLE SESSAO_SALA(
ID_SESSAO_FILIAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TIPO_SESSAO_FILME BOOL,
ID_SESSAO INT NOT NULL,
ID_SALA INT NOT NULL,
ID_FILME INT NOT NULL,
CONSTRAINT FK_SESSAO_SESSAO_SALA
	FOREIGN KEY(ID_SESSAO)
    REFERENCES SESSAO(ID_SESSAO),
CONSTRAINT FK_SALA_SESSAO_SALA
	FOREIGN KEY(ID_SALA)
    REFERENCES SALA(ID_SALA),
CONSTRAINT FK_FILME_SESSAO_SALA
	FOREIGN KEY(ID_FILME)
    REFERENCES FILME(ID_FILME)
);

CREATE TABLE ATOR_FILME(
ID_ATOR_FILME INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_ATOR INT NOT NULL,
ID_FILME INT NOT NULL,
CONSTRAINT FK_ATOR_FILME
	FOREIGN KEY(ID_ATOR)
    REFERENCES ATOR(ID_ATOR),
CONSTRAINT FK_FILME_ATOR_FILME
	FOREIGN KEY(ID_FILME)
    REFERENCES FILME(ID_FILME)
);

CREATE TABLE DIRETOR_FILME(
ID_DIRETOR_FILME INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_DIRETOR INT NOT NULL,
ID_FILME INT NOT NULL,
CONSTRAINT FK_DIRETOR_DIRETOR_FILME
	FOREIGN KEY(ID_DIRETOR)
    REFERENCES DIRETOR(ID_DIRETOR),
CONSTRAINT FK_FILME_DIRETOR_FILME
	FOREIGN KEY(ID_FILME)
    REFERENCES FILME(ID_FILME)
);