-- 1. Listar atores e os filmes em que atuam

SELECT
    P.NOME AS ATOR,
    F.TITULO AS FILME
FROM ATOR A
INNER JOIN PESSOA P ON A.ID_PESSOA = P.ID_PESSOA
INNER JOIN FILME F ON A.ID_FILME = F.ID_FILME
ORDER BY F.TITULO;

-- 2. Listar diretores e seus filmes

SELECT
    P.NOME AS DIRETOR,
    F.TITULO AS FILME
FROM DIRETOR D
INNER JOIN PESSOA P ON D.ID_PESSOA = P.ID_PESSOA
INNER JOIN FILME F ON D.ID_FILME = F.ID_FILME
ORDER BY F.TITULO;

-- 3. Quantidade de atores por filme

SELECT
    F.TITULO,
    COUNT(A.ID_ATOR) AS TOTAL_ATORES
FROM FILME F
INNER JOIN ATOR A ON F.ID_FILME = A.ID_FILME
GROUP BY F.ID_FILME
ORDER BY TOTAL_ATORES DESC;

-- 4. Quantidade de diretores por filme

SELECT
    F.TITULO,
    COUNT(D.ID_DIRETOR) AS TOTAL_DIRETORES
FROM FILME F
INNER JOIN DIRETOR D ON F.ID_FILME = D.ID_FILME
GROUP BY F.ID_FILME
ORDER BY TOTAL_DIRETORES DESC;

-- 5. Filmes e seus respectivos diretores

SELECT
    F.TITULO,
    P.NOME AS DIRETOR
FROM FILME F
INNER JOIN DIRETOR D ON F.ID_FILME = D.ID_FILME
INNER JOIN PESSOA P ON D.ID_PESSOA = P.ID_PESSOA
ORDER BY F.TITULO;

-- 6. Filmes e seus respectivos atores

SELECT
    F.TITULO,
    P.NOME AS ATOR
FROM FILME F
INNER JOIN ATOR A ON F.ID_FILME = A.ID_FILME
INNER JOIN PESSOA P ON A.ID_PESSOA = P.ID_PESSOA
ORDER BY F.TITULO;

-- 7. Pessoa que participa de mais filmes como ator

SELECT
    P.NOME,
    COUNT(A.ID_FILME) AS TOTAL_FILMES
FROM PESSOA P
INNER JOIN ATOR A ON P.ID_PESSOA = A.ID_PESSOA
GROUP BY P.ID_PESSOA
ORDER BY TOTAL_FILMES DESC
LIMIT 1;

-- 8. Pessoa que participa de mais filmes como diretor

SELECT
    P.NOME,
    COUNT(D.ID_FILME) AS TOTAL_FILMES
FROM PESSOA P
INNER JOIN DIRETOR D ON P.ID_PESSOA = D.ID_PESSOA
GROUP BY P.ID_PESSOA
ORDER BY TOTAL_FILMES DESC
LIMIT 1;

-- 9. Quantidade de filmes por gênero

SELECT
    GENERO,
    COUNT(*) AS TOTAL_FILMES
FROM FILME
GROUP BY GENERO
ORDER BY TOTAL_FILMES DESC;

-- 10. Filmes com atores e diretores

SELECT
    F.TITULO,
    PA.NOME AS ATOR,
    PD.NOME AS DIRETOR
FROM FILME F
INNER JOIN ATOR A ON F.ID_FILME = A.ID_FILME
INNER JOIN PESSOA PA ON A.ID_PESSOA = PA.ID_PESSOA
INNER JOIN DIRETOR D ON F.ID_FILME = D.ID_FILME
INNER JOIN PESSOA PD ON D.ID_PESSOA = PD.ID_PESSOA
ORDER BY F.TITULO;