DROP SCHEMA IF EXISTS CINEMA;
CREATE SCHEMA CINEMA;
USE CINEMA;

CREATE TABLE ENDERECO(
ID_ENDERECO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CIDADE VARCHAR(30),
ESTADO VARCHAR(30),
BAIRRO VARCHAR(50),
RUA VARCHAR(50),
NUMERO VARCHAR(10)
);

CREATE TABLE EMPRESA(
ID_EMPRESA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_EMPRESA VARCHAR(255) NOT NULL
);

CREATE TABLE FILIAL(
ID_FILIAL INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_FANTASIA VARCHAR(255) NOT NULL,
CNPJ VARCHAR(20),
ID_EMPRESA INT UNIQUE,
ID_ENDERECO INT UNIQUE,
CONSTRAINT FK_FILIAL_EMPRESA
	FOREIGN KEY (ID_EMPRESA)
    REFERENCES EMPRESA(ID_EMPRESA),
CONSTRAINT FK_FILIAL_ENDERECO
	FOREIGN KEY(ID_ENDERECO)
    REFERENCES ENDERECO(ID_ENDERECO)
);

CREATE TABLE SALA(
ID_SALA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
LOTACAO INT NOT NULL,
ID_FILIAL INT NOT NULL,
CONSTRAINT FK_FILIAL_SALA
	FOREIGN KEY(ID_FILIAL)
    REFERENCES FILIAL(ID_FILIAL)
);

CREATE TABLE HORARIO(
ID_HORARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TURNO VARCHAR(255) NOT NULL,
HORARIO DATETIME NOT NULL
);

CREATE TABLE PESSOA(
ID_PESSOA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
NACIONALIDADE VARCHAR(255) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE FILME(
ID_FILME INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TITULO VARCHAR(255) NOT NULL,
GENERO VARCHAR(255) NOT NULL,
DURACAO VARCHAR(255) NOT NULL
);

CREATE TABLE SESSAO(
ID_SESSAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
TIPO_FILME BOOL,
ID_SALA INT NOT NULL,
ID_FILME INT NOT NULL,
ID_HORARIO INT NOT NULL,
CONSTRAINT FK_HORARIO_SESSAO
	FOREIGN KEY(ID_HORARIO)
    REFERENCES HORARIO(ID_HORARIO),
CONSTRAINT FK_SALA_SESSAO
	FOREIGN KEY(ID_SALA)
    REFERENCES SALA(ID_SALA),
CONSTRAINT FK_FILME_SESSAO
	FOREIGN KEY(ID_FILME)
    REFERENCES FILME(ID_FILME)
);

CREATE TABLE INGRESSO(
ID_INGRESSO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DT_COMPRA DATETIME NOT NULL,
VALOR DOUBLE NOT NULL,
ID_PESSOA INT NOT NULL,
ID_SESSAO int not null,
CONSTRAINT FK_INGRESSO_PESSOA
	FOREIGN KEY(ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA),
CONSTRAINT FK_INGRESSO_SESSAO
	FOREIGN KEY(ID_SESSAO)
    REFERENCES SESSAO(ID_SESSAO)
);

CREATE TABLE ATOR(
ID_ATOR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PESSOA INT NOT NULL,
ID_FILME INT NOT NULL,
CONSTRAINT FK_ATOR_PESSOA
	FOREIGN KEY(ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA),
CONSTRAINT FK_ATOR_FILME
	FOREIGN KEY(ID_FILME)
    REFERENCES FILME(ID_FILME)
);

CREATE TABLE DIRETOR(
ID_DIRETOR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PESSOA INT NOT NULL,
ID_FILME INT NOT NULL,
CONSTRAINT FK_DIRETOR_PESSOA
	FOREIGN KEY(ID_PESSOA)
    REFERENCES PESSOA(ID_PESSOA),
CONSTRAINT FK_DIRETOR_FILME
	FOREIGN KEY(ID_FILME)
    REFERENCES FILME(ID_FILME)
);