DROP SCHEMA IF EXISTS ESCOLA;
CREATE DATABASE ESCOLA;
USE ESCOLA;

CREATE TABLE SALA(
ID_SALA BIGINT NOT NULL AUTO_INCREMENT,
CAPACIDADE INT (3) NOT NULL,
ANDAR INT (2) NOT NULL,
PRIMARY KEY (ID_SALA)
)
ENGINE=INNODB;

CREATE TABLE ALUNO(
ID INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR (255),
EMAIL VARCHAR (255),
TELEFONE VARCHAR (255),
ALTURA DECIMAL (3,2),
PRIMARY KEY (ID)
)
ENGINE=INNODB;


INSERT INTO SALA (CAPACIDADE, ANDAR) VALUES (40, 1);
INSERT INTO SALA (CAPACIDADE, ANDAR) VALUES (35, 1);
INSERT INTO SALA (CAPACIDADE, ANDAR) VALUES (38, 2);
INSERT INTO ALUNO (NOME, EMAIL, TELEFONE, ALTURA) VALUES ('JONAS MAIA', 'MAIA@NOSSODOMINIO.COM.BR', 1112345548, 1.76);
INSERT INTO ALUNO (NOME, EMAIL, TELEFONE, ALTURA) VALUES ('JOAO CLEBER', 'CLEBER@NOSSODOMINIO.COM.BR', 1112235548, 1.94);

UPDATE ALUNO
SET EMAIL = 'JONASMAIA@NOSSODOMINIO.COM.BR'
WHERE ID = 1;

UPDATE SALA
SET CAPACIDADE = 30
WHERE ID_SALA = 1;

DELETE FROM SALA
WHERE ID_SALA = 3;

SELECT * FROM SALA;
SELECT * FROM ALUNO;