DROP SCHEMA IF EXISTS HOSPITAL;
CREATE SCHEMA HOSPITAL;
USE HOSPITAL;

CREATE TABLE ADDRESS(
ID_ADDRESS INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NEIGHBORHOOD VARCHAR(255) NOT NULL,
STREET VARCHAR(255) NOT NULL,
CEP VARCHAR(8) NOT NULL,
HOUSE_NUMBER VARCHAR(10) NOT NULL
);

CREATE TABLE PERSON(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
PHONE VARCHAR(20) NOT NULL,
RG VARCHAR(20) NOT NULL UNIQUE,
CPF VARCHAR(11) NOT NULL UNIQUE,
SEX VARCHAR (10) NOT NULL,
CIVIL_STATUS VARCHAR(20) NOT NULL,
BIRTH_DATE DATE NOT NULL,
ID_ADDRESS INT NOT NULL,
CONSTRAINT FK_PERSON_ADDRESS
	FOREIGN KEY(ID_ADDRESS)
	REFERENCES ADDRESS(ID_ADDRESS)
);

CREATE TABLE PATIENT(
ID_PATIENT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ID_PERSON INT NOT NULL,
CONSTRAINT FK_PATIENT_PERSON
	FOREIGN KEY(ID_PERSON)
    REFERENCES PERSON(ID)
);

CREATE TABLE EMERGENCY_CONTACT(
ID_EMERGENCY_CONTACT INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
PHONE VARCHAR(20) NOT NULL,
ID_PERSON INT NOT NULL,
CONSTRAINT FK_EMERGENCY_CONTACT_ID_PERSON
	FOREIGN KEY(ID_PERSON)
    REFERENCES PERSON(ID)
);

CREATE TABLE DOCTOR(
ID_DOCTOR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CRM VARCHAR(20) NOT NULL UNIQUE,
ID_PERSON INT NOT NULL,
CONSTRAINT FK_DOCTOR_PERSON
	FOREIGN KEY(ID_PERSON)
    REFERENCES PERSON(ID)
);

CREATE TABLE CONSULTATION(
ID_CONSULTATION INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CONSULTATION_DATE DATETIME NOT NULL,
DIAGNOSIS VARCHAR(255) NOT NULL,
ID_DOCTOR INT NOT NULL,
ID_PATIENT INT NOT NULL,
CONSTRAINT FK_CONSULTATION_DOCTOR
	FOREIGN KEY(ID_DOCTOR)
    REFERENCES DOCTOR(ID_DOCTOR),
CONSTRAINT FK_CONSULTATION_PATIENT
	FOREIGN KEY(ID_PATIENT)
    REFERENCES PATIENT(ID_PATIENT)
);

select * from consultation;
