-- HIGOR KLEEMANN E BRUNO FURLAN

CREATE DATABASE CURSOS_PALESTRAS;

USE CURSOS_PALESTRAS;

CREATE TABLE PESSOA(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATETIME NOT NULL
);

CREATE TABLE MINICURSO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_CURSO VARCHAR(50) NOT NULL,
    DATA_INICIO DATETIME NOT NULL,
    DATA_FIM DATETIME NOT NULL
);

CREATE TABLE PALESTRA(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_PALESTRA VARCHAR(50) NOT NULL,
    DATA_PALESTRA DATETIME NOT NULL
);

CREATE TABLE ESCOLA(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME_ESCOLA VARCHAR(50) NOT NULL,
    ENDEREÇO VARCHAR(50)
);

CREATE TABLE INSCRICAO(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATA_INSCRICAO DATETIME NOT NULL,
    ID_PESSOA INT NOT NULL,
    ID_MINICURSO INT NOT NULL,
    ID_PALESTRA INT NOT NULL,
    ID_ESCOLA INT NOT NULL,
    CONSTRAINT FK_ID_PESSOA_INSCRICAO
		FOREIGN KEY (ID_PESSOA)
        REFERENCES PESSOA(ID),
    CONSTRAINT FK_ID_MINICURSO_INSCRICAO
		FOREIGN KEY (ID_MINICURSO)
        REFERENCES MINICURSO(ID),
    CONSTRAINT FK_ID_PALESTRA_INSCRICAO
		FOREIGN KEY (ID_PALESTRA)
        REFERENCES PALESTRA(ID),
    CONSTRAINT FK_ID_ESCOLA_INSCRICAO
		FOREIGN KEY (ID_ESCOLA)
        REFERENCES ESCOLA(ID)
);