-- INNER JOIN

SELECT
	NF.NRO_NOTA, NF.NM_CLIENTE,
    COUNT(INF.COD_PRODUTO) AS QTD,
    SUM(INF.VL_TOTAL) AS TOTAL
FROM
	NOTA_FISCAL AS NF
INNER JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
GROUP BY NF.NRO_NOTA
ORDER BY QTD, TOTAL DESC;

SELECT
	NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF
INNER JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
INNER JOIN PRODUTO AS P
	ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;

-- LEFT JOIN
-- RETORNA OS REGISTROS QUE ESTAO NA TABELA A ESQUERDA
-- (MESMO QUE NAO ESTEJAM A DIREITA) E OS REGISTROS DA
-- TABELA A DIREITA QUE SAO COMINS A ELA.

SELECT
	NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF
LEFT JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
LEFT JOIN PRODUTO AS P
	ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;

-- RIGHT JOIN
-- USAMOS PARA EXIBIR OS REGISTROS QUE ESTAO NA TABELA
-- A DIREITA (MESMO QUE NAO ESTEJAM NA TABELA A
-- ESQUERDA) E OS REGISTROS DA TABELA A ESQUERDA
-- QUE SAO COMUNS A DIREITA

SELECT
	NF.NRO_NOTA, NF.NM_CLIENTE, P.DESC_PRODUTO
FROM NOTA_FISCAL AS NF
RIGHT JOIN ITEM_NOTA_FISCAL AS INF
	ON NF.NRO_NOTA = INF.NRO_NOTA
RIGHT JOIN PRODUTO AS P
	ON INF.COD_PRODUTO = P.COD_PRODUTO
ORDER BY NF.NRO_NOTA ASC;