DROP SCHEMA IF EXISTS LIVRARIA;
CREATE DATABASE LIVRARIA;
USE LIVRARIA;

CREATE TABLE EDITORA(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL,
ANO_NASCIMENTO DATETIME NOT NULL,
NACIONAL BOOL NOT NULL
)
ENGINE=INNODB;

INSERT INTO EDITORA (NOME, EMAIL, ANO_NASCIMENTO, NACIONAL) VALUES ('LIVROS BONITOS', 'LIVRARIALIVROSBONITOS@LIVROS.COM.BR', '1999-01-01', 1);
INSERT INTO EDITORA (NOME, EMAIL, ANO_NASCIMENTO, NACIONAL) VALUES ('LIVRARIA LEITURA', 'LIVRARIALEITURA@LIVROS.COM.BR', '1980-01-01', 1);
INSERT INTO EDITORA (NOME, EMAIL, ANO_NASCIMENTO, NACIONAL) VALUES ('LEIA LIVROS', 'LEIALIVROS@LIVROS.COM.BR', '1990-01-01', 1);

UPDATE EDITORA SET NACIONAL = 0 WHERE ID = 2;
UPDATE EDITORA SET NOME = 'LIVRARIA LIVROS BONITOS' WHERE ID = 1;
UPDATE EDITORA SET EMAIL = 'LIVRARIALEIALIVROS@LIVROS.COM.BR' WHERE ID = 3;

DELETE FROM EDITORA WHERE ID = 3;

SELECT * FROM EDITORA;