-- CRIAR BD
CREATE DATABASE GREENHOUSE;

-- DEFINIR BD COMO PADRÃO / UTILIZÁVEL
USE GREENHOUSE;

-- CRIAR TABELA/ENTIDADE //nome, tipo, configurações
CREATE TABLE `PLANTS` (
	`PLANT_NAME` CHAR(30) NOT NULL,
    `SENSOR_VALUE` FLOAT DEFAULT NULL,
    `SENSOR_EVENT` TIMESTAMP NOT NULL
		DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY `PK_PLANTS` (`PLANT_NAME`) 
);

-- VISUALIZAR TODAS AS OCORRÊNCIAS EM PLANTS
-- LISTAR TODOS OS REGISTROS DE DADOS // UTILIZASSE O ASTERISCO
SELECT * FROM PLANTS;

-- VISUALIZAR COLUNAS ESPECÍFICAS
SELECT PLANT_NAME, SENSOR_VALUE, SENSOR_EVENT
FROM PLANTS;

-- INSERIR DADOS NA TABELA/ENTIDADE PLANTS
INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE)
VALUES ('Rosa', 0.2319);

-- INSERIR MÚLTIPLOS REGISTROS DE UMA VEZ
INSERT INTO PLANTS (PLANT_NAME, SENSOR_VALUE)
VALUES
	('Cactus', 0.2411), ('Girassol', 0.3112), ('Orquídea', 0.4102), ('Lírio', 0.5566);

-- CONSULTA APLICANDO FILTROS // SELECIONE TODAS AS PLANTAS DA TABELA PLANT_NAME QUE SÃO CACTUS
SELECT * FROM PLANTS
WHERE PLANT_NAME = 'Cactus';

-- FILTROS COMPOSTOS COM OPERADORES AND OR XOR ETC // <> DIFERENTE // < MENOR // > MAIOR
SELECT * FROM PLANTS
WHERE PLANT_NAME <> 'CANNABIS'
AND SENSOR_VALUE < 0.5566
AND SENSOR_VALUE > 0.2411;