

CREATE TABLE PESSOA(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(255),
BIRTH_DATE DATETIME NOT NULL,
ADDRESS VARCHAR(255)
);

CREATE TABLE MINICURSO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_CURSO VARCHAR(255),
DATA_INICIO DATETIME NOT NULL,
DATA_FIM DATETIME NOT NULL
);

CREATE TABLE PALESTRA(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_PALESTRA VARCHAR(255),
DATA_PALESTRA DATETIME NOT NULL
);

CREATE TABLE ESCOLA(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOME_ESCOLA VARCHAR(255),
ENDERECO VARCHAR(255)
);

CREATE TABLE INSCRICAO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DATA_INSCRICAO DATETIME NOT NULL,
ID_PESSOA INT NOT NULL,
ID_MINICURSO INT NOT NULL,
ID_PALESTRA INT NOT NULL,
ID_ESCOLA INT NOT NULL,
CONSTRAINT FK_ID_PESSOA_INSCRICAO
	FOREIGN KEY (ID)
    REFERENCES PESSOA(ID),
CONSTRAINT FK_ID_MINICURSO_INSCRICAO
	FOREIGN KEY (ID)
    REFERENCES MINICURSO(ID),
CONSTRAINT FK_ID_PALESTRA_INSCRICAO
	FOREIGN KEY (ID)
    REFERENCES PALESTRA(ID),
CONSTRAINT FK_ID_ESCOLA_INSCRICAO
	FOREIGN KEY (ID)
    REFERENCES (ESCOLA(ID)
);
